### ISSUE TITLE
ViewsGenerator fails when primary key is set on multiple columns

### ISSUE THREAD

**Issue by pepijnolivier** [bitsoflove/AsgardGenerators#2]
Reproducible steps:

1. forward engineer the attached mysqlworkbench database to an asgard project  [generic-products-translatable.mwb.zip](https://github.com/bitsoflove/AsgardGenerators/files/134423/generic-products-translatable.mwb.zip)  
2. Scaffold a new module: `php artisan asgard:module:scaffold` (use Bitsoflove/Products as the module name)
3. Generate the structure
`php artisan asgard:generate:structure Products --tables=attributes_attributes,attributes_relationships,attributes_translations,attributes,product_version_attributes,prices,currencies,product_version_prices,price_types,product_statuses,product_version_status,product_status_translations,product_version_translations,product_version,teams,products`

Result: fails on `ViewsGenerator`, line 385 (Array to String conversion)
Reason: it assumes `$primary_key` is a string, while it is actually an array.

**Comment by pepijnolivier** [comment]
Replacing that part of the code with the below seems to fix the issue

    $list_keys = '';
    if(is_array($primary_key) && !empty($primary_key)){
        $list_keys = "'" . implode("','", $primary_key) . "'";
    }elseif(!is_array($primary_key)){
        $list_keys = "'$primary_key'";
    }

**Comment by stijntilleman** [comment]
Applied patch to fix this issue
